[package]
name = "sniper"
version = "0.1.0"
authors = ["pablo <pablo.makoki@gmail.com>"]

[dependencies]
rand = "0.4.2"
log = { version = "0.4", optional = true }
serde = { version = "1", optional = true }
serde_derive = { version = "1", optional = true }
separator = "0.3.1"
